name: CI for nuxt.js project test

on:
  push:
    branches:
      - "*"
      - "*/*"
      - "**"
      - "!master"
      - "!dev"
    paths:
      - "**.spec.ts"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: List changed files ( 변경된 파일들 )
        id: changed_files
        run: |
          git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} > changed-files.txt
          echo files=$(cat changed-files.txt) >> $GITHUB_OUTPUT

      - name: Run tests on changed files
        run: |
          FILES=$(echo "${{ steps.changed_files.outputs.files }}" | grep '\.spec.ts$' | tr '\n' ' ')
          FILE_SUFFIX="$(IFS=, ; echo "$FILES")"
          echo "Running tests for: $FILES"
          npm run test:verbose ${FILE_SUFFIX}
